### ISSUE TITLE
反馈个 Docker Compose 部署时的坑子（

### ISSUE THREAD

**Issue by Trumeet** [donwa/oneindex#362]
Docker Compose 部署的时候，如果 Volume 挂载自己的目录就会出现权限问题（因为默认是 root 所有者的）。而 Dockerfile 中的执行 `chown` 是不会被套用在自己挂载的目录上的，只能每次启动时设定。
所以目前的解决方案是通过 `command` 覆盖启动时的默认指令，执行 `chown` 命令后再启动。贴出 `docker-compose.yml` 如下，**望作者把相关指令写进 `Dockerfile` 中的 `CMD` 中**，以便更方便地部署。
```yaml
# docker-compose.yml
version: "3"
services:
    oneindex
            image: yinaoxiong/oneindex
            volumes:
                    - ./Config:/var/www/html/config:rw
                    - ./Cache:/var/www/html/cache:rw
            command: sh -c "chown -R www-data:www-data cache/ config/ & php-fpm & nginx -g 'daemon off;'"
```
万望作者加以修正，以方便部署，多谢！
